### ISSUE TITLE
FlashMessenger translator does not support parameterised string

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc-plugin-flashmessenger#7] opened 2019-12-31 22:35 UTC
The standard format (to my knowledge) of translating a string containing a variable would be:

```<?= sprintf($this->translate(_("Ticket '%s' has been saved"), $ticket->getName()); ?>```

The way FlashMessenger uses the Translator does not allow for such usage, and restricts the user to simple strings. 

I extended the View\Helper\FlashMessenger to allow for the translator to ```sprintf()``` parameters into the string, but that required me to pass an array to the addMessage() like so:

```$this->flashMessenger->setNamespace('xxx')->addMessage([ _("Ticket '%s' has been saved"), $ticket->getName() ]);```

I recently did an ```composer update``` and it came to my attention now that the flashMessenger addMessage() function has changed it's definition to accept only strings.

Am I wrong on this? Should the FlashMessenger view helper be updated or could the addMessage definition become more loose?

---

Originally posted by @twmobius at https://github.com/zendframework/zend-view/issues/140

**Comment by samsonasik** [comment] 2020-07-17 03:53
I transfered the issue. Now in `laminas-mvc-plugin-flashmessenger`

**Comment by froschdesign** [comment] 2022-06-21 07:55
Duplicate of https://github.com/laminas/laminas-i18n/issues/7

**Closed by froschdesign** 2022-06-21 07:55 UTC
Labels: Duplicate
